
import { Criterion, EvaluationRecord } from './types';

export const CAMPUSES = [
  'IPG Kampus Pendidikan Teknik',
  'IPG Kampus Perempuan Melayu',
  'IPG Kampus Melaka',
  'IPG Kampus Raja Melewar',
  'IPG Kampus Bahasa Antarabangsa'
];

export const DEPARTMENTS = [
  'Jabatan Matematik',
  'Jabatan Sains',
  'Jabatan Pendidikan Islam',
  'Jabatan Ilmu Pendidikan',
  'Jabatan Bahasa',
  'Jabatan Sains Sosial',
  'Jabatan Pendidikan Teknik dan Vokasional',
  'Jabatan Pengajian Melayu',
  'Jabatan Pendidikan Jasmani dan Kokurikulum',
  
];

// Added department property to each lecturer to resolve type mismatch errors in App.tsx (Lines 167 and 180)
export const LECTURERS = [
 { name: 'Adzli bin Ismail (KJ)',	department: 'Jabatan Pendidikan Islam' },
{ name: 'Ablin a/p Davadason Peter',	department:	'Jabatan Sains' },
{ name: 'Afian Akhbar bin Mustam',	department:	'Jabatan Matematik' },
{ name: 'Ameerul Aswad bin Ab Aziz',	department:	'Jabatan Pengajian Melayu' },
{ name: 'Anida binti Idrus',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Aniza binti Omar',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Azhar bin Hashim (KJ)',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Azlin binti Mohd Rosdi',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Azlina binti Yacob', department:	 'Jabatan Bahasa' },
{ name: 'Azlina Wati binti Hamdan',	department:	'Jabatan Sains Sosial' },
{ name: 'Bahiyah binti A Talip',	department:	 'Jabatan Pendidikan Islam' },
{ name: 'Che Rohani binti Che Aziz',	department:	'Jabatan Pendidikan Jasmani dan Kokurikulum' },
{ name: 'Datin Noor Akmar binti Azlan',	department:	'Jabatan Matematik' },
{ name: 'Dg Bibah binti Ag Tuah',	department:	'Jabatan Sains' },
{ name: 'Dr. Abd.Hadi bin Kudin (KJ)',	department:	'Jabatan Pengajian Melayu' },
{ name: 'Dr. Adila binti Md. Hashim',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Dr. Ajurun Begum binti Ahamed (KJ)', department: 'Jabatan Bahasa' },
{ name: 'Dr. Anusuya a/p Kaliappan',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Dr. Asmah binti Bohari (KJ)',	department:	'Jabatan Sains' },
{ name: 'Dr. Asmah binti Mat Sa ud',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Dr. Azerai bin Azmi',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Baharudin bin Saleh',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Ellyza binti Karim (KJ)',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Fauziah binti Ismail', department:	'Jabatan Bahasa' },
{ name: 'Dr. Gayatri a/p Marimothu',	department:	'Jabatan Pengajian Melayu' },
{ name: 'Dr. Khasturi a/p Ramalingam',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Kok Boon Shiong',	department:	'Jabatan Matematik' },
{ name: 'Dr. Kwan Shwu Shyan',	department:	'Jabatan Sains Sosial' },
{ name: 'Dr. Loh Su Ling',	department:	 'Jabatan Sains' },
{ name: 'Dr. Mohammad Izzuan bin Termedi @Termiji',	department:	'Jabatan Matematik' },
{ name: 'Dr. Mohd Ridzuan bin Padzil',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Dr. Mohd Sukri bin Ma arof',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Muhd Fariz bin Ismail (KJ)',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Noor Haslinda binti Shuib',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Nor Laila binti Md Zain',	department:	'Jabatan Pengajian Melayu' },
{ name: 'Dr. Nur Munirah binti Kamaruzaman',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Rubiah binti Dalail',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Santhi a/p Letchumanan',	department:	'Jabatan Sains Sosial' },
{ name: 'Dr. Shamila Dewi a/p Davadas',	department:	'Jabatan Matematik' },
{ name: 'Dr. Shamsul Nizam bin Kachi Mohideen',	department: 'Jabatan Bahasa' },
{ name: 'Dr. Shanty binti Sai en (KJ)',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Dr. Shasitharan a/l Raman Kutty',	department:	'Jabatan Sains Sosial' },
{ name: 'Dr. Siti Rahayu binti Muhammad',	department:	'Jabatan Pengajian Melayu' },
{ name: 'Dr. Suraya Hani binti Zakaria',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Syakima Ilyana binti Ibrahim',	department: 'Jabatan Sains' },
{ name: 'Dr. Syamsiah binti Mokhtar',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Dr. Tengku Nor Husna binti Tengku Jamil (KJ)',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Dr. Thiru Kali Thevi a/p A.Jayaraman',	department: 'Jabatan Sains' },
{ name: 'Dr. Vadivelan a/l Lohonathan',	department:	'Jabatan Pendidikan Jasmani dan Kokurikulum' },
{ name: 'Dr. Vani a/p Perumal',	department:	'Jabatan Matematik' },
{ name: 'Dr. Zaitun binti Ghazali (KJ)',	department: 'Jabatan Sains' },
{ name: 'Dr. Zurina binti Mustaffa',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Faridah binti Mohamad Saad',	 department:	'Jabatan Pengajian Melayu' },
{ name: 'Fauziah binti Ahmad@ Muhd Zailani',	department:	'Jabatan Pengajian Melayu' },
{ name: 'Fawarni binti Ahmad',	department:	'Jabatan Sains' },
{ name: 'Govindan a/l Kanapathy',	department:	'Jabatan Sains' },
{ name: 'Gurumintarjit Kaur a/p Jangir Singh (KJ)',	department:	'Jabatan Sains Sosial' },
{ name: 'Hanafi bin Khamis',	department: 'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Hapidah binti Ab Razak',	department:	'Jabatan Pendidikan Jasmani dan Kokurikulum' },
{ name: 'Haslinah binti Abdullah',	department:	'Jabatan Sains' },
{ name: 'Hemalatha a/p Ramaya@ Durairajoo',	department:	'Jabatan Sains Sosial' },
{ name: 'Isharae bin Abdul Mosamad',	department:	'Jabatan Pendidikan Jasmani dan Kokurikulum' },
{ name: 'Jaya Murugan a/l Chandran',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'K. Raja a/l M. Kanapathy',	department:	'Jabatan Pendidikan Jasmani dan Kokurikulum' },
{ name: 'Kamal bin Baharom',	department: 'Jabatan Sains Sosial' },
{ name: 'Kamalularifin bin Muhamed',	department:	'Jabatan Pendidikan Jasmani dan Kokurikulum' },
{ name: 'Khairullah bin Mokhtar',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Lee Kim Hong', department: 'Jabatan Bahasa' },
{ name: 'Lokman Hakim bin Muhammed',	department: 'Jabatan Matematik' },
{ name: 'Maheskumar a/l Krishnan', department: 'Jabatan Bahasa' },
{ name: 'Mahidin bin Awang Itam',	department:	'Jabatan Pengajian Melayu' },
{ name: 'Manisah binti Mohd Shah',	department:	'Jabatan Matematik' },
{ name: 'Maznah @ Azmah binti Mersin',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Meor Aris bin Meor Hamzah',	department:	'Jabatan Sains Sosial' },
{ name: 'Mohamad Raffe bin Ghalil Abbas',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Mohamed Shariff bin Salehuadin',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Mohammad Effandi bin Othman',	department:	'Jabatan Sains Sosial' },
{ name: 'Mohd Asri bin Abdul Aziz',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Mohd Fitri Firdauz bin Mohd Nor',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Mohd Huzaifah bin Abdul Rahman',	department:	'Jabatan Sains Sosial' },
{ name: 'Mohd Kashfi bin Mohd Jailani',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Mohd Nizam bin Ijom',	department:	'Jabatan Sains' },
{ name: 'Mohd Syafiq bin Abu Hanipah',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Mohd Tazli bin Mahat',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Mohd Zainal Abidin bin Che Mood',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Mohd. Amin bin Said',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Muhammad bin Ibrahim',	department:	'Jabatan Sains' },
{ name: 'Muhammad Hilal bin Arshad',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Noor Aqilah binti Abdul Latiff Janaton',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Noor Aziah binti Mohd Noor',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Noor Marlina binti Mohamed Nor',	department:	'Jabatan Pendidikan Jasmani dan Kesihatan' },
{ name: 'Noraziah binti Mhd Yusop',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Norimah binti Mohd Salleh',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Norliha binti Jemain',	department:	'Jabatan Matematik' },
{ name: 'Norsida binti Ibrahim',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Norsyazana binti Kamarudin',	department:	'Jabatan Matematik' },
{ name: 'Norsyazwani binti Muhamad Dah',	department:	'Jabatan Sains' },
{ name: 'Norzeha binti Othman',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Nur Fatihathul Amin binti Abdul Aziz',	department:	'Jabatan Matematik' },
{ name: 'Nur Rashidah Khairunnisa Ranjeeta binti Abdullah',	department: 'Jabatan Bahasa' },
{ name: 'Rabi ah binti Abd. Rahman',	department:	'Jabatan Pendidikan Jasmani dan Kokurikulum' },
{ name: 'Ramli bin Setapa',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Reshma a/p Rajasaigran',	department:	 'Jabatan Bahasa' },
{ name: 'Roziah binti Anuar',	department:	'Jabatan Sains' },
{ name: 'Ruba ie bin Said',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Sarimah binti Mokhtar',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Sh. Nabilatul Huda binti Syed Abdullah',	department: 'Jabatan Pendidikan Islam' },
{ name: 'Shaharudin bin Saad',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Shamsharizal bin Abd Aziz (KJ)',	department:	'Jabatan Pendidikan Jasmani dan Kokurikulum' },
{ name: 'Sharon Vijaya a/p Balakrishnan',	department: 'Jabatan Bahasa' },
{ name: 'Sheela Devi a/p Veerasamy',	department: 'Jabatan Bahasa' },
{ name: 'Sohaini binti Rejab',	department:	'Jabatan Pengajian Melayu' },
{ name: 'Su Yit Mun',	department:	'Jabatan Bahasa' },
{ name: 'Suzana binti Harun (KJ)',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Tan Sok Phiaw',	department:	'Jabatan Pengajian Melayu' },
{ name: 'Tan Soo Hun',	department:	'Jabatan Sains Sosial' },
{ name: 'Ts. Dr. Mohamed Nazul bin Ismail (KJ)',	department: 'Jabatan Ilmu Pendidikan' },
{ name: 'Ts. Dr. Nur Ain binti Baharin',	department: 'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Ts. En. Khu Eian Chun',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Vilashini a/p Alagandaran',	department:	 'Jabatan Matematik' },
{ name: 'Wahadatul Arta iah binti Saaudi',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Wan Amalia binti Wan Sulaiman (KJ)',	department:	'Jabatan Matematik' },
{ name: 'Wan Nur Fuziana binti Abdol Jani',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Wan Salsa Biila binti Wan Norudin',	department:	'Jabatan Pendidikan Islam' },
{ name: 'Zamry bin Ibrahim',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },
{ name: 'Zanariah binti Mohd Idris',	department:	'Jabatan Matematik' },
{ name: 'Zanariah binti Sipon',	department:	'Jabatan Ilmu Pendidikan' },
{ name: 'Zanariah binti Wahab',	department: 'Jabatan Pengajian Melayu' },
{ name: 'Zawiah binti Bahrom',	department: 'Jabatan Pengajian Melayu' },
{ name: 'Zolkeple bin Ibrahim',	department:	'Jabatan Pendidikan Jasmani dan Kokurikulum' },
{ name: 'Zul Azmi bin Mokhlas',	department:	'Jabatan Pendidikan Teknik dan Vokasional' },

];

export const EVALUATORS = [
 'Dr. Muhaida Akmal binti Mohamad (TP)',
 'Adzli bin Ismail (KJ)',
 'Afian Akhbar bin Mustam',		
 'Ameerul Aswad bin Ab Aziz',	
 'Azlina binti Yacob', 
 'Azhar bin Hashim (KJ)',
 'Dr. Abd.Hadi bin Kudin (KJ)',
 'Dr. Ajurun Begum binti Ahamed (KJ)',
 'Dr. Asmah binti Bohari (KJ)',
 'Dr. Ellyza binti Karim (KJ)',
 'Dr. Mohd Ridzuan bin Padzil',		
 'Dr. Muhd Fariz bin Ismail (KJ)',
 'Dr. Shamsul Nizam bin Kachi Mohideen',	
 'Dr. Shanty binti Sai en (KJ)',
 'Dr. Shasitharan a/l Raman Kutty',	
 'Dr. Suraya Hani binti Zakaria',
 'Dr. Zaitun binti Ghazali (KJ)',
 'Dr. Tengku Nor Husna binti Tengku Jamil (KJ)',
 'Govindan a/l Kanapathy',	
 'Gurumintarjit Kaur a/p Jangir Singh (KJ)',
 'Kamalularifin bin Muhamed',	
 'Meor Aris bin Meor Hamzah',	
 'Mohamad Raffe bin Ghalil Abbas',	
 'Mohd Asri bin Abdul Aziz',	
 'Mohd Huzaifah bin Abdul Rahman',		
 'Mohd Tazli bin Mahat',	
 'Norzeha binti Othman',	
 'Rabi ah binti Abd. Rahman',	
 'Ramli bin Setapa',	
 'Ruba ie bin Said',		
 'Sh. Nabilatul Huda binti Syed Abdullah',	
 'Shamsharizal bin Abd Aziz (KJ)',
 'Tan Sok Phiaw',		
 'Ts. Dr. Mohamed Nazul bin Ismail (KJ)',
 'Ts. En. Khu Eian Chun',		
 'Wan Amalia binti Wan Sulaiman (KJ)',	
 'Zamry bin Ibrahim',	
 'Zanariah binti Sipon',	
 'Zul Azmi bin Mokhlas',
 'Suzana binti Harun (KJ)',
];

export const CREDIT_OPTIONS = ['1', '2', '3', '4'];

export const COMMON_COURSES = [
  { code: 'BAMB1134',	name: 'KEMAHIRAN BERBAHASA ARAB 1' },
{ code: 'BAMB3313',	name: 'KURIKULUM DAN PENTAKSIRAN BAHASA ARAB SEKOLAH RENDAH' },
{ code: 'BCNB3223',	name: 'STRATEGI PENGAJARAN DAN PEMBELAJARAN BAHASA CINA' },
{ code: 'BCNB3263',	name: 'PEDAGOGI KEMAHIRAN MEMBACA' },
{ code: 'BCNB3273',	name: 'PEDAGOGI KEMAHIRAN MENGARANG' },
{ code: 'BMMB1104',	name: 'KESUSASTERAAN DAN KEBUDAYAAN MELAYU' },
{ code: 'BMMB1114',	name: 'PENGENALAN SISTEM EJAAN JAWI DAN RUMI' },
{ code: 'BMMB1124',	name: 'LITERASI BAHASA' },
{ code: 'BMMB1144',	name: 'KESANTUNAN BERBAHASA' },
{ code: 'BMMB3203',	name: 'MORFOLOGI BAHASA MELAYU' },
{ code: 'BMMB3213',	name: 'KURIKULUM BAHASA MELAYU SEKOLAH RENDAH' },
{ code: 'BMMB3223',	name: 'PENGAJARAN KEMAHIRAN BAHASA DALAM BAHASA MELAYU' },
{ code: 'BMMB3243',	name: 'PENGAJARAN SENI BAHASA DAN TATABAHASA DALAM BAHASA MELAYU' },
{ code: 'BMMB3253',	name: 'ASAS PENYELIDIKAN DALAM PENDIDIKAN BAHASA MELAYU' },
{ code: 'BMMB3262',	name: 'KREATIVITI DAN ESTETIKA DALAM PENDIDIKAN BAHASA MELAYU' },
{ code: 'BMMB3283',	name: 'KESUSASTERAAN KANAK-KANAK DALAM PENDIDIKAN BAHASA MELAYU' },
{ code: 'BMMB3293',	name: 'PENTAKSIRAN DALAM PENDIDIKAN BAHASA MELAYU' },
{ code: 'BMMB3333',	name: 'PENGANTAR BAHASA MELAYU' },
{ code: 'BTMB1172',	name: 'SENI PERTUTURAN BAHASA TAMIL' },
{ code: 'EDUP2102',	name: 'SOSIOLOGI DALAM PENDIDIKAN' },
{ code: 'EDUP2112',	name: 'TEKNOLOGI DAN MEDIA PENGAJARAN' },
{ code: 'EDUP2132',	name: 'PROFESIONALISME KEGURUAN' },
{ code: 'EDUP3113',	name: 'PSIKOLOGI PEMBELAJARAN' },
{ code: 'EDUP3113i',	name: 'PSYCHOLOGY OF LEARNING' },
{ code: 'EDUP3143',	name: 'SOSIOLOGI DALAM PENDIDIKAN' },
{ code: 'EDUP3153',	name: 'PENTAKSIRAN DALAM PENDIDIKAN' },
{ code: 'EDUP3163',	name: 'PROFESIONALISME KEGURUAN DAN KEPIMPINAN GURU' },
{ code: 'ELEP4023',	name: 'KESIHATAN MENTAL DALAM PENDIDIKAN' },
{ code: 'ELEP4133',	name: 'KAJIAN MASA DEPAN' },
{ code: 'ELMK2073R',	name: 'PEDAGOGI PENDIDIKAN MORAL SEKOLAH RENDAH' },
{ code: 'ELMK2082R',	name: 'PENTAKSIRAN DALAM PENDIDIKAN MORAL SEKOLAH RENDAH' },
{ code: 'ELMK2102R',	name: 'INOVASI DIGITAL DALAM PEMBENTUKAN MORAL SEKOLAH RENDAH' },
{ code: 'ELMK3103',	name: 'NILAI-NILAI MURNI DARIPADA PERSPEKTIF PELBAGAI AGAMA DAN MASYARAKAT' },
{ code: 'ELMK3133',	name: 'METODOLOGI PENGAJARAN DAN PEMBELAJARAN PENDIDIKAN MORAL' },
{ code: 'ELMK3142',	name: 'PERANCANGAN DAN PELAKSANAAN PENGAJARAN DAN PEMBELAJARAN DALAM PENDIDIKAN MORAL' },
{ code: 'GAPD1032',	name: 'ASAS PEMBELAJARAN DIGITAL' },
{ code: 'GPPP1092',	name: 'PENGANTAR PENGAJIAN PENDIDIKAN' },
{ code: 'GPPP1092i',	name: 'INTRODUCTION TO EDUCATIONAL STUDIES' },
{ code: 'MPU2082',	name: 'BINA INSAN GURU' },
{ code: 'MPU3212',	name: 'BINA INSAN GURU' },
{ code: 'MPU3312',	name: 'PENDIDIKAN ISLAM' },
{ code: 'MPU3322',	name: 'PENDIDIKAN MORAL' },
{ code: 'MPU3411',	name: 'KOKURIKULUM - OLAHRAGA' },
{ code: 'MPU3431a',	name: 'KOKURIKULUM – UNIT BERUNIFORM PENGAKAP I' },
{ code: 'MPU3441a',	name: 'KOKURIKULUM – UNIT BERUNIFORM PASUKAN PANDU PUTERI KADET I' },
{ code: 'MPU3451a',	name: 'KOKURIKULUM – UNIT BERUNIFORM BULAN SABIT MERAH MALAYSIA I' },
{ code: 'MPU3461a',	name: 'KOKURIKULUM – UNIT BERUNIFORM PERGERAKAN PUTERI ISLAM MALAYSIA I' },
{ code: 'MPU3471a',	name: 'KOKURIKULUM – UNIT BERUNIFORM KADET REMAJA SEKOLAH I' },
{ code: 'MPU3481a',	name: 'KOKURIKULUM – UNIT BERUNIFORM KOR SISPA I' },
{ code: 'MTES1104',	name: 'ALGEBRA' },
{ code: 'MTES1114',	name: 'BASIC GEOMETRY' },
{ code: 'MTES1124',	name: 'PRE CALCULUS' },
{ code: 'MTES1132',	name: 'APPRECIATION OF MATHEMATICS' },
{ code: 'MTES1142',	name: 'COMPUTATIONAL THINKING IN MATHEMATICS' },
{ code: 'MTES3213',	name: 'FINANCIAL MATHEMATICS' },
{ code: 'MTES3213',	name: 'FINANCIAL MATHEMATICS' },
{ code: 'MTES3223',	name: 'GEOMETRY' },
{ code: 'MTES3223',	name: 'GEOMETRY' },
{ code: 'MTES3232',	name: 'CURRICULUM STUDIES AND LEARNING THEORIES IN PRIMARY SCHOOL MATHEMATICS' },
{ code: 'MTES3232',	name: 'CURRICULUM STUDIES AND LEARNING THEORIES IN PRIMARY SCHOOL MATHEMATICS' },
{ code: 'MTES3243',	name: 'TEACHING AND ASSESSMENT OF NUMBERS AND OPERATIONS, RELATIONSHIP AND ALGEBRA' },
{ code: 'MTES3263',	name: 'FUNDAMENTALS OF MATHEMATICS EDUCATIONAL RESEARCH' },
{ code: 'MTES3273',	name: 'TEACHING AND ASSESSMENT OF MEASUREMENT AND GEOMETRY STATISTICS AND PROBABILITY' },
{ code: 'MTES3273',	name: 'TEACHING AND ASSESSMENT OF MEASUREMENT, GEOMETRY, STATISTICS AND PROBABILITY' },
{ code: 'MUZK3323',	name: 'ENSEMBEL NYANYIAN' },
{ code: 'MUZK3483',	name: 'ASAS KEMAHIRAN NYANYIAN' },
{ code: 'PAKL1032',	name: 'ASAS SENI KULINARI' },
{ code: 'PALS1012',	name: 'ASAS KELESTARIAN DAN TEKNOLOGI HIJAU' },
{ code: 'PASR1052',	name: 'ASAS SENI DAN REKAAN' },
{ code: 'PEAM1092',	name: 'EKSPLORASI AKTIVITI MUZIKAL' },
{ code: 'PIMK1104',	name: 'PENGANTAR ULUM AL-QURAN DAN ULUM AL-HADIS' },
{ code: 'PIMK1114',	name: 'PENGAJIAN JAWI DAN KHAT' },
{ code: 'PIMK1124',	name: 'SIRAH NABAWIYYAH DAN TARIKH' },
{ code: 'PIMK3243',	name: 'PENGAJIAN AKHLAK ISLAMIAH' },
{ code: 'PIMK3253',	name: 'PENGAJIAN HADIS' },
{ code: 'PIMK3263',	name: 'PENGAJIAN KURIKULUM DAN PENTAKSIRAN PENDIDIKAN ISLAM SEKOLAH RENDAH' },
{ code: 'PIMK3423',	name: 'AKIDAH ISLAMIAH' },
{ code: 'PJMS3213',	name: 'PENGURUSAN PENTADBIRAN PENDIDIKAN JASMANI DAN SUKAN' },
{ code: 'PJMS3263',	name: 'KURIKULUM DAN PEDAGOGI PENDIDIKAN JASMANI' },
{ code: 'PJMS3273',	name: 'PENTAKSIRAN DALAM PENDIDIKAN JASMANI DAN SUKAN' },
{ code: 'PJMS3363',	name: 'PENGAJARAN PENDIDIKAN JASMANI' },
{ code: 'PPSJ1132',	name: 'KEMAHIRAN PEMIKIRAN SEJARAH' },
{ code: 'PRJP4013',	name: 'PROJEK PENYELIDIKAN PENDIDIKAN 1' },
{ code: 'PRJP4023',	name: 'PROJEK PENYELIDIKAN PENDIDIKAN 2' },
{ code: 'PSRE1122',	name: 'SUKAN DAN REKREASI' },
{ code: 'PSVK3433',	name: 'ASAS MEMBUAT CORAK DAN REKAAN' },
{ code: 'PSVK3462',	name: 'KURIKULUM DAN PENTAKSIRAN PENDIDIKAN SENI VISUAL SEKOLAH RENDAH' },
{ code: 'PSVK3473',	name: 'PEDAGOGI PENDIDIKAN SENI VISUAL' },
{ code: 'PSVK3483',	name: 'SENI CATAN' },
{ code: 'RBTS1104',	name: 'ASAS TEKNOLOGI BAHAN DAN PEMBUATAN' },
{ code: 'RBTS1114',	name: 'PENGENALAN PERNIAGAAN DAN KEUSAHAWANAN' },
{ code: 'RBTS1124',	name: 'TEKNOLOGI ELEKTRIK' },
{ code: 'RBTS3263',	name: 'TEKNOLOGI ELEKTRIK DAN ASAS ROBOTIK' },
{ code: 'RBTS3273',	name: 'AMALAN REKA BENTUK DAN TEKNOLOGI' },
{ code: 'RBTS3283',	name: 'TEKNOLOGI TANAMAN SAYURAN DAN HIASAN' },
{ code: 'RBTS3313',	name: 'REKA BENTUK FESYEN' },
{ code: 'RBTS3333',	name: 'ASAS PENYELIDIKAN DALAM PENDIDIKAN' },
{ code: 'RBTS3342',	name: 'INOVASI DIGITAL DALAM PENGAJARAN DAN PEMBELAJARAN' },
{ code: 'RBTS3373',	name: 'REKA BENTUK PENGATURCARAAN' },
{ code: 'RBTS3383',	name: 'PEDAGOGI REKA BENTUK DAN TEKNOLOGI SEKOLAH RENDAH' },
{ code: 'RBTS3383',	name: 'PEDAGOGI REKA BENTUK DAN TEKNOLOGI SEKOLAH RENDAH' },
{ code: 'RBTS3392',	name: 'PENDIDIKAN INKLUSIF' },
{ code: 'RBTS3403',	name: 'ASAS TEKNOLOGI ELEKTRIK DAN ELEKTRONIK' },
{ code: 'RBTS3452',	name: 'ASAS PENGATURCARAAN' },
{ code: 'SCES1104',	name: 'FUNDAMENTALS OF BIOLOGY II' },
{ code: 'SCES1114',	name: 'FUNDAMENTALS OF PHYSICS II' },
{ code: 'SCES1124',	name: 'FUNDAMENTALS OF CHEMISTRY II' },
{ code: 'SCES1134',	name: 'TRENDS AND ISSUES IN SCIENCE EDUCATION' },
{ code: 'SCES3283',	name: 'FUNDAMENTALS OF RESEARCH IN SCIENCE EDUCATION' },
{ code: 'SCES3292',	name: 'SCIENTIFIC SKILLS AND THE MANAGEMENT OF SCIENCE LABORATORY' },
{ code: 'SCES3292',	name: 'SCIENTIFIC SKILLS AND THE MANAGEMENT OF SCIENCE LABORATORY' },
{ code: 'SJHK3213',	name: 'SEJARAH ISLAM SEHINGGA ZAMAN KERAJAAN ABBASIYAH' },
{ code: 'SJHK3373',	name: 'PENGAJIAN KURIKULUM DAN PENTAKSIRAN SEJARAH SEKOLAH RENDAH' },
{ code: 'TERP4034',	name: 'KAEDAH PENYELIDIKAN LANJUTAN' },
{ code: 'TERP4043',	name: 'PEDAGOGI KEPELBAGAIAN BUDAYA' },
{ code: 'TSLB1104',	name: 'GRAMMAR IN CONTEXT' },
{ code: 'TSLB1114',	name: 'LANGUAGE SKILLS IN ACADEMIC CONTEXT' },
{ code: 'TSLB1124',	name: 'LITERARY STUDIES IN ENGLISH' },
{ code: 'TSLB3282',	name: 'ENGLISH LANGUAGE SKILLS 2' },
{ code: 'TSLB3293',	name: 'CHILDREN AND LANGUAGES' },
{ code: 'TSLB3303',	name: 'THEORY AND PRACTICE IN PRIMARY ENGLISH LANGUAGE TEACHING 1' },
{ code: 'TSLB3483',	name: 'STORYTELLING IN THE PRIMARY ESL CLASSROOOM' },
{ code: 'TSLB3523',	name: 'ENGLISH PHONETICS AND PHONOLOGY' },
];

export const EVALUATION_CRITERIA: Criterion[] = [
  // 1. RMK Implementation 
  { id: '1a', category: '1. Pensyarah melaksanakan pengajaran dan pembelajaran mengikut Ringkasan Maklumat Kursus (RMK)/Maklumat Kursus dari aspek:', text: 'a. Kandungan' },
  { id: '1b', category: '1. Pensyarah melaksanakan pengajaran dan pembelajaran mengikut Ringkasan Maklumat Kursus (RMK)/Maklumat Kursus dari aspek:', text: 'b. Aras kognitif, psikomotor dan afektif' },
  { id: '1c', category: '1. Pensyarah melaksanakan pengajaran dan pembelajaran mengikut Ringkasan Maklumat Kursus (RMK)/Maklumat Kursus dari aspek:', text: 'c. Kemahiran insaniah' },
  { id: '1d', category: '1. Pensyarah melaksanakan pengajaran dan pembelajaran mengikut Ringkasan Maklumat Kursus (RMK)/Maklumat Kursus dari aspek:', text: 'd. Pentaksiran' },
  { id: '1e', category: '1. Pensyarah melaksanakan pengajaran dan pembelajaran mengikut Ringkasan Maklumat Kursus (RMK)/Maklumat Kursus dari aspek:', text: 'e. Jumlah jam pembelajaran' },
  
  // 2. Teaching Activity (RESTORED)
  { id: '2a', category: '2. Pensyarah melaksanakan aktiviti pengajaran dan pembelajaran dengan', text: 'a. Terancang dan tersusun.' },
  { id: '2b', category: '2. Pensyarah melaksanakan aktiviti pengajaran dan pembelajaran dengan', text: 'b. Jelas dan berkesan' },
  { id: '2c', category: '2. Pensyarah melaksanakan aktiviti pengajaran dan pembelajaran dengan', text: 'c. penuh keyakinan' },
  { id: '2d', category: '2. Pensyarah melaksanakan aktiviti pengajaran dan pembelajaran dengan', text: 'd. Menarik dan menyeronokkan' },
  { id: '2e', category: '2. Pensyarah melaksanakan aktiviti pengajaran dan pembelajaran dengan', text: 'e. penuh semangat (passionate)' },
  { id: '2f', category: '2. Pensyarah melaksanakan aktiviti pengajaran dan pembelajaran dengan', text: 'f. Melibatkan keseluruhan pelajar' },

  // 3. Student Involvement
  { id: '3a', category: '3. Pensyarah berusaha meningkatkan penglibatan pelajar melalui aktiviti yang', text: 'a. Mencabar' },
  { id: '3b', category: '3. Pensyarah berusaha meningkatkan penglibatan pelajar melalui aktiviti yang', text: 'b. Meransang pemikiran kreatif dan inovatif' },

  // 4. Feedback - Added "a. " to match user request for row 4
  { id: '4a', category: '4. Maklum Balas', text: 'Pensyarah memberi maklum balas dan berusaha memberi bimbingan kepada pelajar.' },

  // 5. Motivasi - Added "a. " for consistency
  { id: '5a', category: '5. Motivasi', text: 'Pensyarah berusaha memotivasikan pelajar' },

  // 6. Sahsiah - Added "a. " for consistency
  { id: '6a', category: '6. Sahsiah', text: 'Pensyarah berusaha membina sahsiah guru yang penyayang, prihatin, penyabar dan bertanggungjawab.' },
];

export const INITIAL_RECORDS: EvaluationRecord[] = [
  {
    id: '1',
    timestamp: Date.now(),
    campus: 'IPG Kampus Pendidikan Teknik',
    department: 'Jabatan Ilmu Pendidikan',
    lecturerName: 'Dr. Ahmad Bin Ismail',
    course: 'Programming Fundamentals',
    code: 'CS101',
    credit: '3',
    date: '2023-11-20',
    evaluatorName: 'Dr. Kamarulzaman bin Ab. Aziz (KJ)',
    scores: { 
      '1a': 4, '1b': 5, '1c': 4, '1d': 4, '1e': 4, 
      '2a': 4, '2b': 5, '2c': 4, '2d': 3, '2e': 5, '2f': 4, 
      '3a': 4, '3b': 5, '4a': 5, '5a': 4, '6a': 5 
    },
    itemRemarks: {},
    remarks: 'Penyampaian sangat berkesan dan melibatkan ramai pelajar aktif.'
  }
];
